### ISSUE TITLE
About ops var and possible use case

### ISSUE THREAD

**Issue by felixsanz** [rstacruz/markdown-it-decorate#15]
I'm processing my files server side, so i don't need the use case for markdown parsers like GitHub.

Also, i prefer `{:target="_blank"}` syntax.

It is possible to add something like:

```javascript
.use(require('markdown-it-decorate'), {
  open: '{',
  close: '}',
})
```

and

```javascript
if (ops.open && ops.close) {
  var tagExpr = new RegExp(ops.open + "?\{(?:([a-z0-9]+)(\^[0-9]*)?: ?)?(.*)\} ?" + ops.close, "g");
} else {
  var tagExpr = /^<!-- ?\{(?:([a-z0-9]+)(\^[0-9]*)?: ?)?(.*)\} ?-->\n?$/
}
```

Or something like that? I would make a pull-request but i'm unable to achieve it, too complex for me

**Comment by felixsanz** [comment]
damn, i'm sorry for this. I just noticed that the brackets are already there, just nested with html comments. So no point in this!

**Comment by rstacruz** [comment]
so you'd prefer `{:.foo}` over `{.foo}`?

**Comment by rstacruz** [comment]
hmm... i think `{:.foo}` will actually work. it'd be like doing `{h2:.foo}` without `h2`.

**Comment by felixsanz** [comment]
nah! this works as expected, i was confused first about the html comments. but i think its not a big deal

**Comment by rstacruz** [comment]
heheh, alright! :)
