### ISSUE TITLE
Error: Unexpected Token

### ISSUE THREAD

**Issue by alinex** [rstacruz/markdown-it-decorate#3]
/node_modules/markdown-it-decorate/index.js:71
      omissions.forEach((idx) => { tokens.splice(idx, 1) })
                               ^
     SyntaxError: Unexpected token >

Maybe you added coffeescript directly into an javascript file!

Should that better be:

    omissions.forEach((function(_this) {
      return function(idx) {
        return tokens.splice(idx, 1);
      };
    })(this));

That's what coffeescript will make out of it.

**Comment by rstacruz** [comment]
> Maybe you added coffeescript directly into an javascript file!

es6 :) node 4.0 supports it.

**Comment by rstacruz** [comment]
but alright, fine, let's make it compatible for older node versions.

**Comment by rstacruz** [comment]
okay, done, released as v1.2... even node v0.10 should be able to use it.

btw: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions — upgrade your node.js ;)

**Comment by alinex** [comment]
That's great my production machine is debian 7 with node 0.10. I will look if it is possible to upgrade sometime.

**Comment by rstacruz** [comment]
yeah man... v0.10 is ancient by 2016 standards :p
